
book_catagories = ["Biographies & Memoirs", "Classics", "Health & Fitness", "History", "Money & Finance", "Self Help"]

books = {"Atomic Habits": ["James Clear", "Self Help",""], 
"The Four Agreements":["", "", ""], 
"Rich Dad Poor Dad": ["Robert Kiyosaki", "Money & Finance", ""], 
"Think and Grow Rich": ["Napoleon Hill", "Money & Finance", ""],
"The Richest Man in Babylon": ["George S. Clason", "Money & Finance", ""],
"How to Win Friends and Influence People": ["Dale Carnegie", "Self Help", ""],
"You are a Badass": ["Jen Sincero", "Self Help", ""],
"Deep Work": ["Cal Newport", "Self Help", ""],
"Never Split the Difference": ["Chriss Voss", "Money & Finance", ""],
"The 4-hour Workweek": ["Timothy Ferris", "Money & Finance", ""],
"A Beginners Guide to the Stock Market": ["Matthew R. Kratter", "Money & Finance", ""],
"Why We Sleep": ["Matthew Walker PhD", "Health & Fitness", ""],
"Sapiens: A Brief History of Human Kind": ["Yuval Noah Harari", "History", ""],
"A Short History of Nearly Everything": ["Bill Bryson", "History", ""],
"The Art of War": ["Sun Tzu", "Classics", ""],
"Meditations": ["Marcus Aurelius", "Classics", ""],
"The Lean Startup": ["Eric Ries", "Money & Finance", ""],
"The Little Book that Still Beats the Market": ["Joel Greenblatt", "Money & Finance", ""],
"Money: Master the Game": ["Tony Robbins", "Money & Finance", ""],
"Don Quixote": ["Miguel de Cervantes", "Classics", ""],
"The Prince" : ["Niccolo Machiavelli", "Classics", ""],
"The Republic" : ["Plato", "Classics", ""],
"The Arabian Nights (Tales of 1001 Nights)": ["", "Classics", ""],
"The Illiad & The Odyssey": ["Homer", "Classics", ""],
"Paradise Lost" : ["John Milton", "Classics", ""],
}